sbatch jobs/addition/entropy/surgical.sh
sbatch jobs/addition/entropy/mfc20.sh
sbatch jobs/addition/entropy/adult.sh
sbatch jobs/addition/entropy/bank_marketing.sh
sbatch jobs/addition/entropy/flight_delays1.sh
sbatch jobs/addition/entropy/flight_delays2.sh
sbatch jobs/addition/entropy/flight_delays3.sh
sbatch jobs/addition/entropy/flight_delays4.sh
sbatch jobs/addition/entropy/flight_delays5.sh
sbatch jobs/addition/entropy/diabetes1.sh
sbatch jobs/addition/entropy/diabetes2.sh
sbatch jobs/addition/entropy/diabetes3.sh
sbatch jobs/addition/entropy/diabetes4.sh
sbatch jobs/addition/entropy/diabetes5.sh
sbatch jobs/addition/entropy/skin1.sh
sbatch jobs/addition/entropy/skin2.sh
sbatch jobs/addition/entropy/skin3.sh
sbatch jobs/addition/entropy/skin4.sh
sbatch jobs/addition/entropy/skin5.sh
sbatch jobs/addition/entropy/census.sh
sbatch jobs/addition/entropy/twitter.sh
sbatch jobs/addition/entropy/gas_sensor1.sh
sbatch jobs/addition/entropy/gas_sensor2.sh
sbatch jobs/addition/entropy/higgs1.sh
sbatch jobs/addition/entropy/higgs2.sh
sbatch jobs/addition/entropy/higgs3.sh
sbatch jobs/addition/entropy/higgs4.sh
sbatch jobs/addition/entropy/higgs5.sh