sbatch jobs/amortize/surgical.sh
sbatch jobs/amortize/mfc20.sh
sbatch jobs/amortize/adult.sh
sbatch jobs/amortize/bank_marketing.sh
sbatch jobs/amortize/flight_delays1.sh
sbatch jobs/amortize/flight_delays2.sh
sbatch jobs/amortize/diabetes1.sh
sbatch jobs/amortize/diabetes2.sh
sbatch jobs/amortize/skin1.sh
sbatch jobs/amortize/skin2.sh
sbatch jobs/amortize/skin3.sh
sbatch jobs/amortize/skin4.sh
sbatch jobs/amortize/skin5.sh
sbatch jobs/amortize/census.sh
sbatch jobs/amortize/twitter.sh
sbatch jobs/amortize/gas_sensor1.sh
sbatch jobs/amortize/gas_sensor2.sh
sbatch jobs/amortize/higgs1.sh
sbatch jobs/amortize/higgs2.sh
sbatch jobs/amortize/higgs3.sh
sbatch jobs/amortize/higgs4.sh
sbatch jobs/amortize/higgs5.sh