sbatch jobs/amortize/entropy/surgical.sh
sbatch jobs/amortize/entropy/mfc20.sh
sbatch jobs/amortize/entropy/adult.sh
sbatch jobs/amortize/entropy/bank_marketing.sh
sbatch jobs/amortize/entropy/flight_delays1.sh
sbatch jobs/amortize/entropy/flight_delays2.sh
sbatch jobs/amortize/entropy/diabetes1.sh
sbatch jobs/amortize/entropy/diabetes2.sh
sbatch jobs/amortize/entropy/skin1.sh
sbatch jobs/amortize/entropy/skin2.sh
sbatch jobs/amortize/entropy/skin3.sh
sbatch jobs/amortize/entropy/skin4.sh
sbatch jobs/amortize/entropy/skin5.sh
sbatch jobs/amortize/entropy/census.sh
sbatch jobs/amortize/entropy/twitter.sh
sbatch jobs/amortize/entropy/gas_sensor1.sh
sbatch jobs/amortize/entropy/gas_sensor2.sh
sbatch jobs/amortize/entropy/higgs1.sh
sbatch jobs/amortize/entropy/higgs2.sh
sbatch jobs/amortize/entropy/higgs3.sh
sbatch jobs/amortize/entropy/higgs4.sh
sbatch jobs/amortize/entropy/higgs5.sh