sbatch jobs/delete_until_retrain/gini/surgical.sh
sbatch jobs/delete_until_retrain/gini/mfc20.sh
sbatch jobs/delete_until_retrain/gini/adult.sh
sbatch jobs/delete_until_retrain/gini/bank_marketing.sh
sbatch jobs/delete_until_retrain/gini/flight_delays.sh
sbatch jobs/delete_until_retrain/gini/diabetes.sh
sbatch jobs/delete_until_retrain/gini/skin1.sh
sbatch jobs/delete_until_retrain/gini/skin2.sh
sbatch jobs/delete_until_retrain/gini/census.sh
sbatch jobs/delete_until_retrain/gini/twitter.sh
sbatch jobs/delete_until_retrain/gini/gas_sensor.sh
sbatch jobs/delete_until_retrain/gini/higgs1.sh
sbatch jobs/delete_until_retrain/gini/higgs2.sh