sbatch jobs/delete_until_retrain/entropy/surgical.sh
sbatch jobs/delete_until_retrain/entropy/mfc20.sh
sbatch jobs/delete_until_retrain/entropy/adult.sh
sbatch jobs/delete_until_retrain/entropy/bank_marketing.sh
sbatch jobs/delete_until_retrain/entropy/flight_delays.sh
sbatch jobs/delete_until_retrain/entropy/diabetes.sh
sbatch jobs/delete_until_retrain/entropy/skin1.sh
sbatch jobs/delete_until_retrain/entropy/skin2.sh
sbatch jobs/delete_until_retrain/entropy/census.sh
sbatch jobs/delete_until_retrain/entropy/twitter.sh
sbatch jobs/delete_until_retrain/entropy/gas_sensor.sh
sbatch jobs/delete_until_retrain/entropy/higgs1.sh
sbatch jobs/delete_until_retrain/entropy/higgs2.sh