sbatch jobs/delete_until_retrain/surgical.sh
sbatch jobs/delete_until_retrain/mfc20.sh
sbatch jobs/delete_until_retrain/adult.sh
sbatch jobs/delete_until_retrain/bank_marketing.sh
sbatch jobs/delete_until_retrain/flight_delays.sh
sbatch jobs/delete_until_retrain/diabetes.sh
sbatch jobs/delete_until_retrain/skin1.sh
sbatch jobs/delete_until_retrain/skin2.sh
sbatch jobs/delete_until_retrain/census.sh
sbatch jobs/delete_until_retrain/twitter.sh
sbatch jobs/delete_until_retrain/gas_sensor.sh
sbatch jobs/delete_until_retrain/higgs1.sh
sbatch jobs/delete_until_retrain/higgs2.sh